name: chm_ios
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0  

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.2.15
  permission_handler: ^11.3.1
  image_picker: ^0.8.7+5
  url_launcher: ^6.3.2

  flutter_pdfview: ^1.3.2
  printing: ^5.13.3
  path_provider: ^2.1.5
  pdf: ^3.11.0

  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Fondo_Azul.png
    - assets/Logo_contorno_blanco.png
    - assets/animacion6.gif
    - assets/FondoBlanco.jpeg
    - assets/BOTONERA.jpg
    - assets/GanchoSeguridad.jpeg
    - assets/cableAcero.jpeg
    - assets/polipastos_electricos.webp
    - assets/polipasto_neumatico.png
    - assets/poli_cadena_m.webp
    - assets/poli_palanca.jpg
    - assets/Serv_Instalacion.jpeg
    - assets/Serv_MantePrev.jpeg
    - assets/Serv_Rep_E.jpeg
    - assets/Serv_Inspeccion.jpeg
    - assets/P_Proyectos.jpeg
    - assets/P_Servicios.jpeg
    - assets/Polipastos_Anim.jpeg
    - assets/P_Patines.jpeg
    - assets/Monito_Servicios.png
    - assets/Monito_Cap.png
    - assets/Monito_Cap_Acces.png
    - assets/M_C_Portada.png
    - assets/GRILLETE_DE_CARGA.webp
    - assets/ESTROBO_DE_CARGA.jpg
    - assets/POLEA.webp
    - assets/TIRFOR.webp
    - assets/MOSQUETON.jpg
    - assets/ESLINGA_DE_CADENA.jpg
    - assets/CADENAS_DE_ELEVACION.avif
    - assets/ESLINGA_DE_POLIESTER.jpg
    - assets/TENSOR.webp
    - assets/RODAMIENTOS.jpg
    - assets/POLEA_CON_GANCHO.jpg
    - assets/GUIAS_DE_CABLE.webp
    - assets/TROLE.webp
    - assets/LIMITADOR.png
    - assets/CABLE_ALIMENTACION.webp
    - assets/logochm.png
    - assets/admin_avatar.png
    - assets/animacion2.gif
    - assets/monito-ruega.gif
    - assets/fondodocumentos.jpg
    - assets/fondousuario3.gif
    - assets/CURSO_POLIPASTO.png
    - assets/GRUAS_VIAJERAS.jpg
    - assets/BOMBAS.jpg
    - assets/Tirfor.png
    - assets/PORTADA_CAP.png
    - assets/P_PROYECTOS.png
    - assets/PROYECTOS.png
    - assets/M_POLIPASTO.png
    - assets/GRUA_BANDERA.png
    - assets/GRUA_PORTICO_ELEC.jpg
    - assets/GRUA_PORTICO_MAN.webp
    - assets/GRUA_MONORRIEL.png
    - assets/MANEJO_GRUAS.png
    - assets/CAP_ENERPAC.png
    - assets/ACCESORIOS.png
    - assets/FRENOS.jpeg
    - assets/CONTACTORES.png
    - assets/SEGURO_DE_GANCHO.jpg
    - assets/GUIA_DE_CADENA.jpeg
    - assets/GUARDA_CADENA.png
    - assets/BOBINAS.jpeg
    - assets/NUEZ_DE_CARGA.jpg
    - assets/ENGRANE.jpg
    - assets/FLECHA.jpg
    - assets/RUEDA_TROLE.webp
    - assets/PATIN_H.png
    - assets/MINI_MONTA_MANUAL.png
    - assets/CARGA_TAMBOS.png
    - assets/RODAJA.jpg
    - assets/CAP_PRINCI.png
    - assets/P_SERVICIOS.png
    - assets/PORTICO_ELECTRICA.png

flutter_launcher_icons:
  android: true
  ios: false   
  image_path: "assets/logo.png"